---
- name: Prepare for Docker Install
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - awscli
    state: present

- name: Add Docker GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT Repo
  apt_repository:
    repo: deb [arch={{ ansible_facts.ansible_architecture }}] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    state: present

- name: Install Docker
  apt:
    name: docker-ce docker-compose-plugin docker-ce-cli containerd.io docker-buildx-plugin
    state: present

- name: Create dir for Container env
  file:
    path: /opt/peertube
    state: directory

- name: 