---
- name: Update apt sources
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install postgresql
  ansible.builtin.apt:
    name: "postgresql"
    state: latest

- name: 
  
