---
- name: Install apt packages for elsodos
  ansible.builtin.apt:
    pkg:
      - curl
    state: latest
    update_cache: yes
  become: true

- name: Install yarn
  ansible.builtin.command: "npm install --global yarn"
  become: true

...
  
