---
- name: Install apt packages for elsodos
  ansible.builtin.apt:
    pkg:
      - curl
      - unzip
      - vim
      - wget
      - nodejs
      - npm
      - python3-dev
      - python3-pip
      - python-is-python3
      - certbot
      - nginx
      - ffmpeg
      - postgresql
      - postgresql-contrib
      - openssl
      - g++
      - make
      - redis-server
      - git
      - cron
    state: latest
    update_cache: yes
  become: true

- name: Install yarn
  ansible.builtin.command: "npm install --global yarn"
  become: true

...
  
