---
- name: Include PeerTube Server Tasks
  ansible.builtin.include_tasks:
    file: peertube.yml

- name: Include MINIO S3 Server Tasks
  ansible.builtin.include_tasks:
    file: minio.yml
  when: LOCALS3 = "present"
...
