---
- name: Define MOTD
  ansible.builtin.template:
    src: motd.txt.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
  become: true

- name: Add Debian unstable repo to apt sources
  ansible.builtin.apt_repository:
    repo: deb https://deb.debian.org/debian unstable main contrib non-free
    state: "{{ DEBUNSTABLEREPO }}"
  become: true

- name: Set Repo Pin Prio for Debian unstable
  ansible.builtin.file:
    src: files/90-unstable.pref
    dest: /etc/apt/preferences.d/90-unstable
    owner: root
    group: root
    mode: 0644
  when: DEBUNSTABLEREPO = "present"
  become: true

- name: Install basic apt packages
  ansible.builtin.apt:
    pkg:
      - vim
      - curl
      - git
      - wget
    state: latest
    update_cache: yes
  become: true
    
- name: Update apt sources
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes
  become: true

- name: Upgrade the OS
  ansible.builtin.apt:
    upgrade: dist
    update_cache: yes
  become: true

- name: Reboot machine and send message
  ansible.builtin.reboot:
    msg: "Rebooting host"
  become: true

...
